### ISSUE TITLE
咦，咋不更新了？转行了吗？

### ISSUE THREAD

**Issue by daizimi** [brianway/java-learning#21]

**Comment by beabigboss** [comment]
NOW，I start to be a beach,&nbsp; one job can make money on zhe bed.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月28日(周五) 上午10:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [brianway/java-learning] 咦，咋不更新了？转行了吗？ (#21)

**Comment by daizimi** [comment]
wawoo, sounds cool.

**Comment by beabigboss** [comment]
Get money so tm fast.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月28日(周五) 上午10:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [brianway/java-learning] 咦，咋不更新了？转行了吗？ (#21)




 
wawoo, sounds cool.

**Comment by daizimi** [comment]
> Get money so tm fast.
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年5月28日(周五) 上午10:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [brianway/java-learning] 咦，咋不更新了？转行了吗？ (#21) wawoo, sounds cool. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

咋赚的？

**Comment by beabigboss** [comment]
unsubscribe



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月28日(周五) 下午2:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [brianway/java-learning] 咦，咋不更新了？转行了吗？ (#21)




 
Closed #21.
